name: RedPacketHunt
version: 2.0.0
main: com.example.redpackethunt.RedPacketHunt
api-version: 1.21
commands:
  rph:
    description: 游戏主命令
    usage: /rph <start|stop|setspawn|setduration>
    permission: rph.admin
permissions:
  rph.admin:
    description: 管理员权限
    default: op
